// <auto-generated />
using HomeTech.Services.ComplaintAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeTech.Services.ComplaintAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230912025137_SeedComplaintTable")]
    partial class SeedComplaintTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeTech.Services.ComplaintAPI.Models.Complaint", b =>
                {
                    b.Property<int>("ComplaintID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplaintID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComplaintID");

                    b.ToTable("Complaints");

                    b.HasData(
                        new
                        {
                            ComplaintID = 1,
                            Category = "Plumber",
                            Description = "Water is draining out from the damaged position",
                            Service = "Pipe Leakage"
                        },
                        new
                        {
                            ComplaintID = 2,
                            Category = "Electrician",
                            Description = "While Switching it on/off it is throwing sparks",
                            Service = "Switch Replacement"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
